---

# docker stack deploy -c stack.yml rolling
# Modify the value of `image` to `redis:3.0.7`, then:
# docker stack deploy -c stack.yml rolling

version: "3.4"

services:
  redis:
    #image: redis:3.0.6
    image: "redis:${REDIS_VERSION}"
    # image version update to 3.0.7
    #image: redis:3.0.7
    networks:
      - test_rolling_update
    stop_grace_period: 10s
    deploy:
      #placement:
        # https://docs.docker.com/engine/reference/commandline/service_create/#specify-service-constraints-constraint
        #constraints:
          #- node.role == manager
          #- engine.labels.operatingsystem == ubuntu 14.04 
        #preferences:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        # order: stop-first   # Support v3.4+, stop-first is default

  nginx:
    image: nginx:alpine
    networks:
      - test_rolling_update
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback

networks:
  test_rolling_update:
